language: node_js
addons:
  sauce_connect:
    username: maiermic
  jwt:
    secure: emPImtGhSiuh7koHW6dcql7HsvefODDnDkzpSCMBZ2oiEPBoq16VFtd7OeB5NbrsYOTRCvcDv4kJSsIU9VzBAfkLKrSGxfqddReK65DbUtJCSpWJ2B0MTr8xUo1npdiJxYhBHflViR5t8fYM1jBdrW6jE+aB1lpmMqo5zU6JAZp+hEtpu2px75BYfgIO8g6cBumkY+PWt0UPzxEyWrnS05K53jPbBV8stG3or85KP+yUixdKpdkLNddaMGjrEZ7HEhBZ38Nd7X8U6EA6XJ3pRP+AeO3AQNIgqoEqaLSjyotzbD97dPWJpbd+g2WZvXnXTq3LS+5/MiZEBe7jU8WGpknINXZkOZw5vhwYnl9xEsDnjF01Ml0U15ARmfc2GOF3AvHC2rSrapUS2TPXDKkW3L8b662MFXmS19BKbmFBpouCYScTlCNnscsm0XUTSHyEwldPdRRq0Etbfh5YfoI6cJ2PDOjmJpUUlv6ghgDwCVXIWf2vPwmQmioyqYz0ybrcSeZT4bM5Kfs+TxMIxLnj33bMJHLyNPA+/mnL8IR0BHRIvWzKAoWclvee04DmLVaFmUYp1H8shCzas9fAZagyMhtvi9n0Qrz7Ve4jwOwT+j8iY+WiOcaqVu+PGsRRbVDLI35nE4nTHH2iQPC0X/y8CGiT9XPdFu//HIcZqJkQaoM=
